import type { OrbVisualPreset } from '../orb/orbPresets';

export type OrbThemePreset = {
	id: string;
	label: string;
	description: string;
	tags: string[];
	preset: OrbVisualPreset;
};

const makePreset = (preset: OrbVisualPreset): OrbVisualPreset => ({
	uniforms: { ...preset.uniforms },
	particles: preset.particles,
	bloom: { ...preset.bloom },
});

export const ORB_THEME_PRESETS: OrbThemePreset[] = [
	{
		id: 'barbed-wire',
		label: 'Barbed Wire Core',
		description: 'Aggressive barbed wiring and sparks clamped around the orb.',
		tags: ['wire', 'industrial', 'aggressive'],
		preset: makePreset({
			uniforms: {
				color1: '#14141a',
				color2: '#3b3f4a',
				chargeColor: '#f5f5f5',
				chargeLevel: 0.9,
				wobbleIntensity: 1.5,
				patternScale: 1.5,
				fresnelIntensity: 2.2,
				wireIntensity: 1,
				wireThickness: 0.4,
				sparkIntensity: 0.6,
				blackHoleIntensity: 0.2,
				coreRadius: 0.8,
				ringIntensity: 0.1,
				warpStrength: 0.3,
			},
			particles: 220,
			bloom: {
				strength: 0.9,
				threshold: 0.2,
			},
		}),
	},
	{
		id: 'ice',
		label: 'Cryo Bloom',
		description: 'Glacial blues with frozen veins and a chilly bloom falloff.',
		tags: ['ice', 'crystal', 'calm'],
		preset: makePreset({
			uniforms: {
				color1: '#0d2c45',
				color2: '#88d3ff',
				chargeColor: '#b6f5ff',
				chargeLevel: 0.35,
				wobbleIntensity: 1.8,
				patternScale: 3.2,
				fresnelIntensity: 2.6,
				bandStrength: 0.15,
				bandFrequency: 9,
				crackThreshold: 0.88,
				crackSharpness: 2,
				pulseSpeed: 1.8,
				pulseStrength: 0.15,
				facetSteps: 18,
				glitchIntensity: 0.05,
				wireIntensity: 0.05,
				wireThickness: 0.35,
				sparkIntensity: 0.05,
				blackHoleIntensity: 0.1,
				coreRadius: 0.8,
				ringIntensity: 0.15,
				warpStrength: 0.2,
				vineIntensity: 0.15,
				vineWidth: 0.25,
				mossStrength: 0.2,
				flameIntensity: 0,
				flameScale: 1.3,
				flameSpeed: 0.8,
				coreIntensity: 0.1,
				scrapIntensity: 0.05,
				streakStrength: 0.05,
				impactSparkIntensity: 0.05,
				holoIntensity: 0.2,
				scanSpeed: 1.2,
				sludgeIntensity: 0,
				dripScale: 1.1,
				glowStrength: 0.35,
				frostIntensity: 0.85,
				frostSharpness: 16,
			},
			particles: 110,
			bloom: {
				strength: 0.65,
				threshold: 0.18,
			},
		}),
	},
	{
		id: 'nature',
		label: 'Verdant Pulse',
		description: 'Overgrown nature core with chlorophyll glow and spore particles.',
		tags: ['nature', 'growth', 'organic'],
		preset: makePreset({
			uniforms: {
				color1: '#08210f',
				color2: '#59c065',
				chargeColor: '#f0ff8c',
				chargeLevel: 0.5,
				wobbleIntensity: 2.8,
				patternScale: 2.1,
				fresnelIntensity: 1.95,
				bandStrength: 0.28,
				bandFrequency: 5,
				crackThreshold: 0.55,
				crackSharpness: 4,
				pulseSpeed: 3,
				pulseStrength: 0.45,
				facetSteps: 0,
				glitchIntensity: 0.05,
				wireIntensity: 0.05,
				wireThickness: 0.2,
				sparkIntensity: 0.05,
				blackHoleIntensity: 0,
				coreRadius: 0.85,
				ringIntensity: 0.1,
				warpStrength: 0.1,
				vineIntensity: 0.55,
				vineWidth: 0.3,
				mossStrength: 0.5,
				flameIntensity: 0,
				flameScale: 1.1,
				flameSpeed: 1.4,
				coreIntensity: 0.2,
				scrapIntensity: 0.15,
				streakStrength: 0.1,
				impactSparkIntensity: 0.1,
				holoIntensity: 0.05,
				scanSpeed: 0.7,
				sludgeIntensity: 0.2,
				dripScale: 1.4,
				glowStrength: 0.25,
				frostIntensity: 0.05,
				frostSharpness: 6,
			},
			particles: 180,
			bloom: {
				strength: 0.85,
				threshold: 0.12,
			},
		}),
	},
	{
		id: 'nature-vine',
		label: 'Overgrown Core',
		description: 'Spiraling vines and moss creeping over the core.',
		tags: ['nature', 'organic', 'vine'],
		preset: makePreset({
			uniforms: {
				color1: '#06140a',
				color2: '#2f7f3b',
				chargeColor: '#c4ff7a',
				chargeLevel: 0.6,
				wobbleIntensity: 2,
				patternScale: 2,
				fresnelIntensity: 1.4,
				vineIntensity: 1,
				vineWidth: 0.35,
				mossStrength: 0.8,
				flameIntensity: 0,
				blackHoleIntensity: 0,
			},
			particles: 140,
			bloom: {
				strength: 0.7,
				threshold: 0.18,
			},
		}),
	},
	{
		id: 'void',
		label: 'Void Resonance',
		description: 'Deep space void with inverted colors and aggressive bloom.',
		tags: ['void', 'chaos', 'endgame'],
		preset: makePreset({
			uniforms: {
				color1: '#050108',
				color2: '#5c00ff',
				chargeColor: '#ff3fb7',
				chargeLevel: 0.9,
				wobbleIntensity: 3.4,
				patternScale: 0.9,
				fresnelIntensity: 2.9,
				bandStrength: 0.4,
				bandFrequency: 11,
				crackThreshold: 0.35,
				crackSharpness: 7,
				pulseSpeed: 5.5,
				pulseStrength: 0.9,
				facetSteps: 8,
				glitchIntensity: 0.75,
				wireIntensity: 0.3,
				wireThickness: 0.4,
				sparkIntensity: 0.4,
				blackHoleIntensity: 0.5,
				coreRadius: 0.55,
				ringIntensity: 0.7,
				warpStrength: 0.45,
				vineIntensity: 0,
				vineWidth: 0.35,
				mossStrength: 0,
				flameIntensity: 0.5,
				flameScale: 2.2,
				flameSpeed: 3.5,
				coreIntensity: 0.8,
				scrapIntensity: 0.3,
				streakStrength: 0.4,
				impactSparkIntensity: 0.5,
				holoIntensity: 0.4,
				scanSpeed: 3.2,
				sludgeIntensity: 0,
				dripScale: 1.1,
				glowStrength: 0.25,
				frostIntensity: 0.1,
				frostSharpness: 9,
			},
			particles: 320,
			bloom: {
				strength: 1.8,
				threshold: 0.05,
			},
		}),
	},
	{
		id: 'flame-reactor',
		label: 'Flame Reactor',
		description: 'Surging flame corona and overheating core.',
		tags: ['flame', 'reactor', 'volatile'],
		preset: makePreset({
			uniforms: {
				color1: '#2b0500',
				color2: '#f97316',
				chargeColor: '#775822',
				chargeLevel: 1,
				wobbleIntensity: 3,
				patternScale: 0.8,
				fresnelIntensity: 2.5,
				flameIntensity: 1.35,
				flameScale: 2.8,
				flameSpeed: 3.6,
				flameNoiseDetail: 2.6,
				coreIntensity: 1.15,
				scrapIntensity: 0.25,
				streakStrength: 0.2,
				impactSparkIntensity: 0.35,
				glowStrength: 0.32,
			},
			particles: 320,
			bloom: {
				strength: 1.4,
				threshold: 0.12,
			},
		}),
	},
	{
		id: 'ember',
		label: 'Ashen Ember',
		description: 'Smoldering slag core with ember sparks and heavy wobble.',
		tags: ['fire', 'charged'],
		preset: makePreset({
			uniforms: {
				color1: '#1b0501',
				color2: '#f29200',
				chargeColor: '#ffd08a',
				chargeLevel: 0.65,
				wobbleIntensity: 3.1,
				patternScale: 1.4,
				fresnelIntensity: 2.3,
				bandStrength: 0.1,
				bandFrequency: 4,
				crackThreshold: 0.42,
				crackSharpness: 8,
				pulseSpeed: 3.4,
				pulseStrength: 0.35,
				facetSteps: 0,
				glitchIntensity: 0.1,
				wireIntensity: 0.5,
				wireThickness: 0.45,
				sparkIntensity: 0.7,
				blackHoleIntensity: 0.1,
				coreRadius: 0.7,
				ringIntensity: 0.2,
				warpStrength: 0.15,
				vineIntensity: 0,
				vineWidth: 0.3,
				mossStrength: 0,
				flameIntensity: 1.1,
				flameScale: 2.6,
				flameSpeed: 4,
				coreIntensity: 1,
				scrapIntensity: 0.35,
				streakStrength: 0.5,
				impactSparkIntensity: 0.65,
				holoIntensity: 0.05,
				scanSpeed: 1.6,
				sludgeIntensity: 0.1,
				dripScale: 1.3,
				glowStrength: 0.25,
				frostIntensity: 0,
				frostSharpness: 8,
			},
			particles: 220,
			bloom: {
				strength: 1.2,
				threshold: 0.07,
			},
		}),
	},
	{
		id: 'storm',
		label: 'Storm Core',
		description: 'Electric storm trapped inside the orb with arcing pulses.',
		tags: ['storm', 'electric', 'charged'],
		preset: makePreset({
			uniforms: {
				color1: '#020413',
				color2: '#0a8bdc',
				chargeColor: '#8ff7ff',
				chargeLevel: 0.75,
				wobbleIntensity: 2.4,
				patternScale: 1.2,
				fresnelIntensity: 2.7,
				bandStrength: 0.55,
				bandFrequency: 6,
				crackThreshold: 0.5,
				crackSharpness: 5,
				pulseSpeed: 4,
				pulseStrength: 0.7,
				facetSteps: 0,
				glitchIntensity: 0.25,
				wireIntensity: 0.45,
				wireThickness: 0.3,
				sparkIntensity: 0.5,
				blackHoleIntensity: 0.35,
				coreRadius: 0.6,
				ringIntensity: 0.6,
				warpStrength: 0.4,
				vineIntensity: 0.05,
				vineWidth: 0.35,
				mossStrength: 0.05,
				flameIntensity: 0.4,
				flameScale: 1.9,
				flameSpeed: 2.6,
				coreIntensity: 0.6,
				scrapIntensity: 0.45,
				streakStrength: 0.55,
				impactSparkIntensity: 0.6,
				holoIntensity: 0.2,
				scanSpeed: 2.8,
				sludgeIntensity: 0,
				dripScale: 1.1,
				glowStrength: 0.22,
				frostIntensity: 0.02,
				frostSharpness: 9,
			},
			particles: 260,
			bloom: {
				strength: 1.5,
				threshold: 0.09,
			},
		}),
	},
	{
		id: 'aurora',
		label: 'Aurora Drift',
		description: 'Ribbon gradients inspired by polar aurora curtains.',
		tags: ['aurora', 'calm', 'cosmic'],
		preset: makePreset({
			uniforms: {
				color1: '#061125',
				color2: '#5ef7c1',
				chargeColor: '#f4b3ff',
				chargeLevel: 0.4,
				wobbleIntensity: 1.6,
				patternScale: 2.8,
				fresnelIntensity: 2.1,
				bandStrength: 0.45,
				bandFrequency: 12,
				crackThreshold: 0.95,
				crackSharpness: 0.5,
				pulseSpeed: 2,
				pulseStrength: 0.15,
				facetSteps: 0,
				glitchIntensity: 0.05,
				wireIntensity: 0.15,
				wireThickness: 0.2,
				sparkIntensity: 0.15,
				blackHoleIntensity: 0.2,
				coreRadius: 0.78,
				ringIntensity: 0.35,
				warpStrength: 0.25,
				vineIntensity: 0.2,
				vineWidth: 0.25,
				mossStrength: 0.1,
				flameIntensity: 0.15,
				flameScale: 1.8,
				flameSpeed: 1.8,
				coreIntensity: 0.4,
				scrapIntensity: 0.1,
				streakStrength: 0.1,
				impactSparkIntensity: 0.2,
				holoIntensity: 0.35,
				scanSpeed: 2,
				sludgeIntensity: 0,
				dripScale: 1,
				glowStrength: 0.25,
				frostIntensity: 0.2,
				frostSharpness: 12,
			},
			particles: 140,
			bloom: {
				strength: 0.9,
				threshold: 0.16,
			},
		}),
	},
	{
		id: 'event-horizon',
		label: 'Event Horizon',
		description: 'Dark core, bright accretion ring, and warped rim.',
		tags: ['void', 'black hole', 'endgame'],
		preset: makePreset({
			uniforms: {
				color1: '#02010a',
				color2: '#140b2f',
				chargeColor: '#a855f7',
				chargeLevel: 0.4,
				wobbleIntensity: 1,
				patternScale: 1,
				fresnelIntensity: 1.8,
				blackHoleIntensity: 1,
				coreRadius: 0.4,
				ringIntensity: 0.9,
				warpStrength: 0.7,
				wireIntensity: 0,
				vineIntensity: 0,
				flameIntensity: 0,
			},
			particles: 260,
			bloom: {
				strength: 1.2,
				threshold: 0.08,
			},
		}),
	},
	{
		id: 'radiant',
		label: 'Radiant Alloy',
		description: 'High-tech alloy core with metallic gradients and hard bloom.',
		tags: ['tech', 'metallic'],
		preset: makePreset({
			uniforms: {
				color1: '#181b1f',
				color2: '#cce8ff',
				chargeColor: '#fffb9b',
				chargeLevel: 0.55,
				wobbleIntensity: 1.2,
				patternScale: 2.4,
				fresnelIntensity: 3,
				bandStrength: 0.2,
				bandFrequency: 14,
				crackThreshold: 0.85,
				crackSharpness: 1.5,
				pulseSpeed: 2.8,
				pulseStrength: 0.25,
				facetSteps: 12,
				glitchIntensity: 0.05,
				wireIntensity: 0.2,
				wireThickness: 0.3,
				sparkIntensity: 0.25,
				blackHoleIntensity: 0.15,
				coreRadius: 0.7,
				ringIntensity: 0.25,
				warpStrength: 0.25,
				vineIntensity: 0,
				vineWidth: 0.3,
				mossStrength: 0,
				flameIntensity: 0.35,
				flameScale: 1.7,
				flameSpeed: 2.2,
				coreIntensity: 0.5,
				scrapIntensity: 0.15,
				streakStrength: 0.2,
				impactSparkIntensity: 0.25,
				holoIntensity: 0.45,
				scanSpeed: 2.2,
				sludgeIntensity: 0,
				dripScale: 1,
				glowStrength: 0.3,
				frostIntensity: 0.05,
				frostSharpness: 8,
			},
			particles: 90,
			bloom: {
				strength: 1.35,
				threshold: 0.2,
			},
		}),
	},
	{
		id: 'abyss',
		label: 'Abyssal Echo',
		description: 'Deep ocean abyss with bioluminescent motes and low charge.',
		tags: ['water', 'void', 'calm'],
		preset: makePreset({
			uniforms: {
				color1: '#010914',
				color2: '#009fb3',
				chargeColor: '#5af6ff',
				chargeLevel: 0.25,
				wobbleIntensity: 1.1,
				patternScale: 3.6,
				fresnelIntensity: 1.7,
				bandStrength: 0.25,
				bandFrequency: 9,
				crackThreshold: 0.7,
				crackSharpness: 2.5,
				pulseSpeed: 1.6,
				pulseStrength: 0.2,
				facetSteps: 4,
				glitchIntensity: 0.15,
				wireIntensity: 0.1,
				wireThickness: 0.25,
				sparkIntensity: 0.15,
				blackHoleIntensity: 0.05,
				coreRadius: 0.9,
				ringIntensity: 0.1,
				warpStrength: 0.05,
				vineIntensity: 0.25,
				vineWidth: 0.4,
				mossStrength: 0.3,
				flameIntensity: 0,
				flameScale: 1.4,
				flameSpeed: 1,
				coreIntensity: 0.1,
				scrapIntensity: 0.6,
				streakStrength: 0.45,
				impactSparkIntensity: 0.35,
				holoIntensity: 0.05,
				scanSpeed: 0.6,
				sludgeIntensity: 0.45,
				dripScale: 1.6,
				glowStrength: 0.3,
				frostIntensity: 0.02,
				frostSharpness: 7,
			},
			particles: 70,
			bloom: {
				strength: 0.55,
				threshold: 0.22,
			},
		}),
	},
];
